### ISSUE TITLE
Unable to get org.postgresql:r2dbc-postgresql

### ISSUE THREAD

**Issue by Distractic** [komapper/komapper#836] opened 2023-01-11 07:57 UTC
### Describe the bug

According to the [documentation](https://www.komapper.org/docs/quickstart/), I'm trying to use `r2dbc` with `postgresql`.

However, when I retrieve the komapper dependencies, I have the error : 

```
main: Could not find org.postgresql:r2dbc-postgresql:.
Required by:
    project : > org.komapper:komapper-dialect-postgresql-r2dbc:1.6.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Expected behavior

The dependency `org.postgresql:r2dbc-postgresql` must be retrievable

### Actual behavior

The dependency `org.postgresql:r2dbc-postgresql` is not retrieved

### Steps to reproduce the problem

```kt
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.8.0"
    id("com.google.devtools.ksp") version "1.8.0-1.0.8"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    val komapperVersion = "1.6.0"

    platform("org.komapper:komapper-platform:$komapperVersion").let {
        implementation(it)
        ksp(it)
    }
    implementation("org.komapper:komapper-starter-r2dbc")
    implementation("org.komapper:komapper-dialect-postgresql-r2dbc")
    ksp("org.komapper:komapper-processor")

    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "17"
}
```

To fix the issue, we need to add 
`implementation("org.postgresql:r2dbc-postgresql:1.0.0.RELEASE")`

### Versions

- Komapper: 1.6.0
- Kotlin: 1.8.0
- JVM: 17
- JDBC Driver or R2DBC Driver: R2DBC 
- Database: postgresql
- OS: Windows /  Linux

**Comment by nakamura-to** [comment] 2023-01-11 12:05
Hi. Thanks for your report.
This issue is a duplicate of #826.
The fix will be released in the next version.

**Closed by nakamura-to** 2023-01-11 12:05 UTC
Labels: waiting-for-triage
